[package]
name = "shared"
version = "0.0.0-local"
edition = "2024"

[dependencies]
zng.workspace = true
tracing.workspace = true

# dependency license collection & bundling in release builds.
zng-tp-licenses = { version = "0.9.2", features = ["embed"], optional = true }
[build-dependencies]
zng-tp-licenses = { version = "0.9.2", features = ["build"], optional = true }

# use ANGLE on Windows
[target.'cfg(windows)'.dependencies]
zng-view-angle = { version = "0.1", features = ["download"] }

[features]
dev = [
    # enable all default features in dev builds
    "zng/default",
    "zng/config_json",
]
release = [
    # Collect and embed crate licenses
    "dep:zng-tp-licenses",
    # enable default features in release builds, 
    # you can replace this with only features used to optimize binary size
    "zng/default",
    "zng/config_json",
]
